

# Module1 – Introduction to Feature Engineering

**Dataset:** Hotel Booking Demand Dataset

**Objective:** Understand the fundamentals of Feature Engineering and how raw hotel booking data can be converted into useful features for Machine Learning.

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    r"C:\Users\HP\Sprint_6_Feature_Engineering_-_Feature_Selection\data\hotel_bookings.csv"
)

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [2]:
print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

Dataset Shape: (119390, 32)

Columns:
['hotel', 'is_canceled', 'lead_time', 'arrival_date_year', 'arrival_date_month', 'arrival_date_week_number', 'arrival_date_day_of_month', 'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children', 'babies', 'meal', 'country', 'market_segment', 'distribution_channel', 'is_repeated_guest', 'previous_cancellations', 'previous_bookings_not_canceled', 'reserved_room_type', 'assigned_room_type', 'booking_changes', 'deposit_type', 'agent', 'company', 'days_in_waiting_list', 'customer_type', 'adr', 'required_car_parking_spaces', 'total_of_special_requests', 'reservation_status', 'reservation_status_date']

Data Types:
hotel                                 str
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                    str
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                                  str
country                               str
market_segment                        str
distribution_channel                  str
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                    str
assigned_room_type                    str
booking_changes                     int64
deposit_type                          str
agent                             float64
company                           float64
days_in_waiting_list                int64
customer_type                         str
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                    str
reservation_status_date               str
dtype: object

### Observation

The Hotel Booking Demand dataset contains information about hotel reservations, including booking details, guest information, stay duration, room information, market segment, and cancellation status.

The target variable for this dataset is `is_canceled`, where:

- `0` represents a booking that was not canceled.
- `1` represents a booking that was canceled.

The dataset contains both numerical and categorical variables, providing several opportunities for Feature Engineering.

## 1. What is a Feature?

A **feature** is an individual input variable or attribute used by a Machine Learning model to understand the data and make predictions.

In the Hotel Booking Demand dataset, examples of features include:

- `lead_time` – Number of days between booking and arrival.
- `adults` – Number of adults in the booking.
- `children` – Number of children.
- `adr` – Average Daily Rate of the booking.
- `market_segment` – Market segment through which the booking was made.
- `deposit_type` – Type of deposit made for the booking.
- `total_of_special_requests` – Number of special requests made by the customer.

These features provide information that can help a Machine Learning model identify patterns related to hotel booking cancellations.

In [3]:
feature_columns = [
    "lead_time",
    "adults",
    "children",
    "adr",
    "market_segment",
    "deposit_type",
    "total_of_special_requests"
]

df[feature_columns].head()

,lead_time,adults,children,adr,market_segment,deposit_type,total_of_special_requests
0,342,2,0.0,0.0,Direct,No Deposit,0
1,737,2,0.0,0.0,Direct,No Deposit,0
2,7,1,0.0,75.0,Direct,No Deposit,0
3,13,1,0.0,75.0,Corporate,No Deposit,0
4,14,2,0.0,98.0,Online TA,No Deposit,1

### Observation

The selected columns represent different characteristics of hotel bookings.

Numerical features contain measurable values, while categorical features represent different groups or categories. These features can be used as inputs for Machine Learning models.

## 2. Feature vs Variable

A **variable** is any column or attribute that stores information about an observation in a dataset.

A **feature** is a variable that is selected or prepared to be used as an input to a Machine Learning model.

Therefore, every feature is a variable, but not every variable is necessarily used as a feature.

For example, `arrival_date_month` is a variable in the Hotel Booking Demand dataset. It can be converted into a numerical representation such as the arrival month number, which can be used as a Machine Learning feature.

In [4]:
month_mapping = {
    "January": 1,
    "February": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12
}

df["arrival_month_num"] = df["arrival_date_month"].map(month_mapping)

df[["arrival_date_month", "arrival_month_num"]].head()

  arrival_date_month  arrival_month_num
0               July                  7
1               July                  7
2               July                  7
3               July                  7
4               July                  7

### Observation

`arrival_date_month` is the original variable, while `arrival_month_num` is a transformed feature created from it.

The numerical representation can be more convenient for certain Machine Learning algorithms and further feature engineering operations.

## 3. Feature vs Target

A **feature** is an input variable used by a Machine Learning model to make a prediction.

A **target** is the output variable that the model is trained to predict.

In the Hotel Booking Demand dataset, `is_canceled` is the target variable.

- `is_canceled = 0` → Booking was not canceled.
- `is_canceled = 1` → Booking was canceled.

Examples of features that can be used to predict cancellation include `lead_time`, `adr`, `deposit_type`, `market_segment`, and `total_of_special_requests`.

In [5]:
X = df[
    [
        "lead_time",
        "adults",
        "children",
        "adr",
        "total_of_special_requests"
    ]
]

y = df["is_canceled"]

print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

Features:
   lead_time  adults  children   adr  total_of_special_requests
0        342       2       0.0   0.0                          0
1        737       2       0.0   0.0                          0
2          7       1       0.0  75.0                          0
3         13       1       0.0  75.0                          0
4         14       2       0.0  98.0                          1

Target:
0    0
1    0
2    0
3    0
4    0
Name: is_canceled, dtype: int64

### Observation

The feature variables are used as inputs to the Machine Learning model, while `is_canceled` is the target that the model attempts to predict.

Keeping features and the target clearly separated is important when preparing data for Machine Learning.

## 4. What is Feature Engineering?

**Feature Engineering** is the process of creating, transforming, selecting, or extracting useful features from existing data to improve the performance of Machine Learning models.

Raw hotel booking data may contain individual columns that do not directly represent useful business information.

For example, `stays_in_weekend_nights` and `stays_in_week_nights` are separate variables. They can be combined to create a new feature called `total_stay_nights`.

Feature Engineering helps convert raw data into meaningful information that Machine Learning models can use more effectively.

In [6]:
df["total_stay_nights"] = (
    df["stays_in_weekend_nights"] +
    df["stays_in_week_nights"]
)

df[
    [
        "stays_in_weekend_nights",
        "stays_in_week_nights",
        "total_stay_nights"
    ]
].head()

   stays_in_weekend_nights  stays_in_week_nights  total_stay_nights
0                        0                     0                  0
1                        0                     0                  0
2                        0                     1                  1
3                        0                     1                  1
4                        0                     2                  2

### Observation

The new `total_stay_nights` feature combines two existing variables into a single meaningful feature.

This feature gives a clearer representation of the total duration of the customer's stay and may provide useful information for predicting booking behavior.

## 5. Why Feature Engineering?

Feature Engineering is important because raw data is not always in the most useful form for Machine Learning models.

Feature Engineering can help to:

- Create meaningful information from existing variables.
- Represent business relationships more clearly.
- Transform features into suitable formats.
- Reduce unnecessary or redundant information.
- Improve the ability of Machine Learning models to identify patterns.
- Incorporate domain knowledge into the dataset.

For the Hotel Booking Demand dataset, combining weekend and weekday stays into `total_stay_nights` provides a more meaningful representation of the customer's total stay duration.

In [7]:
df[
    [
        "stays_in_weekend_nights",
        "stays_in_week_nights",
        "total_stay_nights",
        "is_canceled"
    ]
].head()

,stays_in_weekend_nights,stays_in_week_nights,total_stay_nights,is_canceled
0,0,0,0,0
1,0,0,0,0
2,0,1,1,0
3,0,1,1,0
4,0,2,2,0

### Observation

The engineered feature `total_stay_nights` summarizes two related variables into one useful feature.

Such features can help Machine Learning models work with information that is closer to the actual business meaning of the data.

## 6. Importance of Domain Knowledge

**Domain Knowledge** means understanding the specific business area or industry from which the data is collected.

Domain knowledge is important in Feature Engineering because it helps us understand what the columns represent, which relationships are meaningful, and which new features can provide useful information to a Machine Learning model.

In the Hotel Booking Demand dataset, understanding hotel booking behavior helps us identify meaningful features such as:

- `lead_time` – A longer booking lead time may be associated with different cancellation behavior.
- `deposit_type` – The type of deposit can provide information about booking commitment.
- `total_of_special_requests` – The number of special requests can represent customer engagement with the booking.
- `total_stay_nights` – The total duration of the stay provides a better representation of the booking than considering weekend and weekday nights separately.

Domain knowledge also helps identify features that should not be used because they contain information that becomes available only after the booking outcome.

In [8]:
# Create a domain-based feature

df["total_stay_nights"] = (
    df["stays_in_weekend_nights"] +
    df["stays_in_week_nights"]
)

df[
    [
        "stays_in_weekend_nights",
        "stays_in_week_nights",
        "total_stay_nights",
        "is_canceled"
    ]
].head()

,stays_in_weekend_nights,stays_in_week_nights,total_stay_nights,is_canceled
0,0,0,0,0
1,0,0,0,0
2,0,1,1,0
3,0,1,1,0
4,0,2,2,0

### Observation

Domain knowledge helps us create features that have a meaningful business interpretation.

In this example, combining weekend and weekday nights gives the `total_stay_nights` feature, which represents the complete duration of a hotel stay.

## 7. Good Features vs Bad Features

Not every variable in a dataset is a good feature for Machine Learning.

A **good feature** provides useful information that is available at the time of prediction and has a meaningful relationship with the target.

A **bad feature** may contain irrelevant information, excessive missing values, redundant information, identifiers, or information that is only available after the target outcome.

For the Hotel Booking Demand dataset:

| Feature | Type | Reason |
|---|---|---|
| `lead_time` | Good | Provides information about booking timing. |
| `adr` | Good | Represents the average daily rate of the booking. |
| `deposit_type` | Good | Provides information about booking commitment. |
| `total_stay_nights` | Good | Represents the complete stay duration. |
| `is_canceled` | Bad as a feature | It is the target variable. |
| `reservation_status` | Bad | It contains information about the final booking outcome. |
| `reservation_status_date` | Bad | It is related to the final reservation status and can cause leakage. |

A feature should be evaluated based on its usefulness, availability at prediction time, and risk of data leakage.

In [9]:
# Compare examples of potentially useful and problematic columns

good_features = [
    "lead_time",
    "adr",
    "deposit_type",
    "total_stay_nights"
]

potentially_bad_features = [
    "is_canceled",
    "reservation_status",
    "reservation_status_date"
]

print("Good Feature Examples:")
print(df[good_features].head())

print("\nPotentially Bad Feature Examples:")
print(df[potentially_bad_features].head())

Good Feature Examples:
   lead_time   adr deposit_type  total_stay_nights
0        342   0.0   No Deposit                  0
1        737   0.0   No Deposit                  0
2          7  75.0   No Deposit                  1
3         13  75.0   No Deposit                  1
4         14  98.0   No Deposit                  2

Potentially Bad Feature Examples:
   is_canceled reservation_status reservation_status_date
0            0          Check-Out              2015-07-01
1            0          Check-Out              2015-07-01
2            0          Check-Out              2015-07-02
3            0          Check-Out              2015-07-02
4            0          Check-Out              2015-07-03

### Observation

Good features provide useful information that can be known when making the prediction.

`reservation_status` and `reservation_status_date` should not be used for predicting cancellation at the time of booking because they contain information related to the final reservation outcome.

The target variable `is_canceled` must also remain separate from the input features.

## 8. Feature Engineering Workflow

Feature Engineering follows a systematic process to convert raw data into useful Machine Learning features.

The typical workflow is:

**Raw Data → Understand Features → Create Features → Transform Features → Select Features → Check Leakage → ML-Ready Features**

For the Hotel Booking Demand dataset, the workflow can be applied as follows:

1. Understand the available hotel booking variables.
2. Identify the target variable `is_canceled`.
3. Create meaningful features from existing variables.
4. Transform features into suitable formats.
5. Select relevant features for the Machine Learning model.
6. Check for data leakage.
7. Prepare the final set of ML-ready features.

For example, `stays_in_weekend_nights` and `stays_in_week_nights` can be combined to create `total_stay_nights`.

In [10]:
# Example of the Feature Engineering workflow

# Feature Creation
df["total_stay_nights"] = (
    df["stays_in_weekend_nights"] +
    df["stays_in_week_nights"]
)

# Select relevant features
selected_features = [
    "lead_time",
    "adults",
    "children",
    "adr",
    "total_stay_nights",
    "total_of_special_requests"
]

feature_data = df[selected_features]

feature_data.head()

,lead_time,adults,children,adr,total_stay_nights,total_of_special_requests
0,342,2,0.0,0.0,0,0
1,737,2,0.0,0.0,0,0
2,7,1,0.0,75.0,1,0
3,13,1,0.0,75.0,1,0
4,14,2,0.0,98.0,2,1

### Observation

The Feature Engineering workflow converts raw hotel booking variables into a more useful feature set.

In this example, `total_stay_nights` is created from two existing variables, and relevant features are selected for further Machine Learning preparation.

Feature creation, transformation, selection, and leakage checking are important steps before using the data for model training.

## 9. Feature Creation

**Feature Creation** is the process of creating new features from existing variables to represent useful information in a more meaningful way.

Feature creation can involve:

- Addition of two or more features.
- Subtraction between features.
- Multiplication or division.
- Ratios and percentages.
- Aggregation of related variables.
- Combining existing information based on domain knowledge.

In the Hotel Booking Demand dataset, `stays_in_weekend_nights` and `stays_in_week_nights` represent different parts of the customer's stay.

We can combine them to create `total_stay_nights`, which represents the complete number of nights booked.

Another useful feature is `total_guests`, created by combining the number of adults, children, and babies.

In [11]:
# Feature 1: Total Stay Nights

df["total_stay_nights"] = (
    df["stays_in_weekend_nights"] +
    df["stays_in_week_nights"]
)

# Feature 2: Total Guests

df["total_guests"] = (
    df["adults"] +
    df["children"] +
    df["babies"]
)

df[
    [
        "stays_in_weekend_nights",
        "stays_in_week_nights",
        "total_stay_nights",
        "adults",
        "children",
        "babies",
        "total_guests"
    ]
].head()

,stays_in_weekend_nights,stays_in_week_nights,total_stay_nights,adults,children,babies,total_guests
0,0,0,0,2,0.0,0,2.0
1,0,0,0,2,0.0,0,2.0
2,0,1,1,1,0.0,0,1.0
3,0,1,1,1,0.0,0,1.0
4,0,2,2,2,0.0,0,2.0

### Observation

Two new features were created from existing hotel booking variables.

- `total_stay_nights` represents the complete duration of the customer's stay.
- `total_guests` represents the total number of people included in the booking.

These engineered features provide a more meaningful representation of the original booking information and can be useful for Machine Learning models.

## 10. Feature Transformation

**Feature Transformation** is the process of changing the representation or scale of existing features so that they are more suitable for Machine Learning models.

Common feature transformation techniques include:

- Log transformation
- Square root transformation
- Power transformation
- Scaling
- Normalization
- Standardization

In the Hotel Booking Demand dataset, `lead_time` represents the number of days between booking and arrival. This feature can have a skewed distribution because some bookings are made much earlier than others.

A log transformation can reduce the effect of very large values and make the distribution more suitable for analysis and Machine Learning.

In [12]:
# Log transformation of lead_time

df["lead_time_log"] = np.log1p(df["lead_time"])

df[["lead_time", "lead_time_log"]].head()

   lead_time  lead_time_log
0        342       5.837730
1        737       6.603944
2          7       2.079442
3         13       2.639057
4         14       2.708050

### Observation

The `lead_time_log` feature is a transformed version of `lead_time`.

The log transformation reduces the impact of very large values and can help handle skewness in numerical features.

In a Machine Learning workflow, transformations should be learned from the training data and then applied to validation and test data to avoid data leakage.

## 11. Feature Selection

**Feature Selection** is the process of selecting the most relevant features for a Machine Learning model and removing features that are unnecessary, redundant, or irrelevant.

Feature selection can help to:

- Reduce the number of input features.
- Remove irrelevant information.
- Reduce model complexity.
- Improve model performance.
- Make the model easier to interpret.
- Reduce the risk of overfitting.

Common Feature Selection methods include:

- **Filter Methods** – Select features using statistical measures such as correlation.
- **Wrapper Methods** – Evaluate different feature subsets using a Machine Learning model.
- **Embedded Methods** – Select important features during model training, such as feature importance from tree-based models.

For the Hotel Booking Demand dataset, features such as `lead_time`, `adr`, and `total_of_special_requests` may provide useful information for predicting `is_canceled`.

In [13]:
# Select numerical features and check their correlation with the target

numeric_features = [
    "lead_time",
    "adults",
    "children",
    "stays_in_weekend_nights",
    "stays_in_week_nights",
    "adr",
    "total_of_special_requests"
]

correlation = df[numeric_features + ["is_canceled"]].corr()["is_canceled"]

correlation.sort_values(ascending=False)

is_canceled                  1.000000
lead_time                    0.293123
adults                       0.060017
adr                          0.047557
stays_in_week_nights         0.024765
children                     0.005048
stays_in_weekend_nights     -0.001791
total_of_special_requests   -0.234658
Name: is_canceled, dtype: float64

### Observation

The correlation values provide an initial indication of the relationship between numerical features and the target variable `is_canceled`.

Features with stronger relationships may be considered for further analysis, while features with very weak relationships may require additional investigation.

Correlation alone should not be used as the final feature selection method. More detailed feature selection techniques will be covered in the later Feature Selection notebook.

## 12. Feature Extraction

**Feature Extraction** is the process of deriving useful information from existing data and representing it as a new feature that can be used by a Machine Learning model.

Feature extraction is commonly used when the original data contains information in a form that is not directly useful for Machine Learning.

In the Hotel Booking Demand dataset, the arrival date information is represented using separate columns such as `arrival_date_year`, `arrival_date_month`, and `arrival_date_day_of_month`.

These columns can be combined to create a complete arrival date and useful information such as the day of the week can then be extracted from it.

In [14]:
# Create a complete arrival date

df["arrival_date"] = pd.to_datetime(
    df["arrival_date_year"].astype(str) + "-" +
    df["arrival_date_month"] + "-" +
    df["arrival_date_day_of_month"].astype(str)
)

# Extract the day of the week

df["arrival_day_of_week"] = df["arrival_date"].dt.day_name()

df[
    [
        "arrival_date_year",
        "arrival_date_month",
        "arrival_date_day_of_month",
        "arrival_date",
        "arrival_day_of_week"
    ]
].head()

,arrival_date_year,arrival_date_month,arrival_date_day_of_month,arrival_date,arrival_day_of_week
0,2015,July,1,2015-07-01,Wednesday
1,2015,July,1,2015-07-01,Wednesday
2,2015,July,1,2015-07-01,Wednesday
3,2015,July,1,2015-07-01,Wednesday
4,2015,July,1,2015-07-01,Wednesday

### Observation

The separate arrival date components were combined to create `arrival_date`.

The day of the week was then extracted from the date and stored as `arrival_day_of_week`.

This creates a new feature from existing information and provides a more useful representation of the arrival date for further analysis and Machine Learning.

## 13. Feature Leakage

**Feature Leakage** occurs when information that would not be available at the time of prediction is used as an input feature for a Machine Learning model.

Feature leakage can cause a model to achieve unrealistically high performance during training and testing, but perform poorly when used on new real-world data.

In the Hotel Booking Demand dataset, `reservation_status` and `reservation_status_date` contain information about the final status of a reservation.

If the goal is to predict whether a booking will be canceled at the time of booking, these columns should not be used as input features because their information becomes available after the booking outcome.

Therefore, these columns should be removed before model training.

In [15]:
# Features that can cause leakage for cancellation prediction

leakage_features = [
    "reservation_status",
    "reservation_status_date"
]

df[leakage_features].head()

  reservation_status reservation_status_date
0          Check-Out              2015-07-01
1          Check-Out              2015-07-01
2          Check-Out              2015-07-02
3          Check-Out              2015-07-02
4          Check-Out              2015-07-03

In [16]:
# Remove leakage-prone features

df_ml = df.drop(columns=leakage_features)

print("Remaining columns:", df_ml.shape[1])
print("Leakage features present:",
      [col for col in leakage_features if col in df_ml.columns])

Remaining columns: 36
Leakage features present: []

### Observation

`reservation_status` and `reservation_status_date` were identified as potential leakage features because they contain information related to the final reservation outcome.

These features should be excluded when building a model that predicts cancellation at the time of booking.

Preventing feature leakage ensures that the Machine Learning model learns from information that would actually be available when making a real-world prediction.

## Role of Feature Engineering in the ML Pipeline

Feature Engineering plays an important role in preparing data for Machine Learning.

The overall Machine Learning workflow can be represented as:

**Raw Data → Data Cleaning → Preprocessing → Feature Engineering → Feature Selection → Model Training → Model Evaluation → Prediction**

In the Hotel Booking Demand dataset:

- **Raw Data:** Original hotel booking information.
- **Data Cleaning:** Handle missing values, duplicates, and invalid values.
- **Preprocessing:** Encode categorical variables and prepare numerical features.
- **Feature Engineering:** Create meaningful features such as `total_stay_nights` and `total_guests`.
- **Feature Selection:** Select relevant features and remove unnecessary or leakage-prone features.
- **Model Training:** Train a Machine Learning model using the prepared features.
- **Model Evaluation:** Evaluate the model using appropriate performance metrics.
- **Prediction:** Use the trained model to predict whether a hotel booking will be canceled.

In [17]:
# Example of the final feature set for the ML pipeline

final_features = [
    "lead_time",
    "adults",
    "children",
    "babies",
    "adr",
    "total_stay_nights",
    "total_guests",
    "total_of_special_requests"
]

X = df[final_features]
y = df["is_canceled"]

print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

X.head()

Feature Shape: (119390, 8)
Target Shape: (119390,)

,lead_time,adults,children,babies,adr,total_stay_nights,total_guests,total_of_special_requests
0,342,2,0.0,0,0.0,0,2.0,0
1,737,2,0.0,0,0.0,0,2.0,0
2,7,1,0.0,0,75.0,1,1.0,0
3,13,1,0.0,0,75.0,1,1.0,0
4,14,2,0.0,0,98.0,2,2.0,1

### Observation

Feature Engineering connects raw business data with Machine Learning by converting existing information into meaningful and useful features.

In this notebook, features such as `total_stay_nights`, `total_guests`, `lead_time_log`, and `arrival_day_of_week` were created or transformed from the original hotel booking data.

The final feature set should contain only information that is appropriate and available at the time of prediction. Leakage-prone features such as `reservation_status` and `reservation_status_date` should be excluded.

Feature Engineering therefore helps prepare the dataset for Feature Selection and subsequent Machine Learning tasks.