# Module 4 - Date & Time Feature Engineering

## 1. Year, Month, Day

### Explanation

Year, Month, and Day features split a date into separate numerical components.

In the Hotel Booking dataset, the arrival date is represented using:

- `arrival_date_year`
- `arrival_date_month`
- `arrival_date_day_of_month`

These values can be used to create a complete arrival date and extract its individual components.

### Example

Arrival Date = 2017-07-15

→ Year = 2017  
→ Month = 7  
→ Day = 15

### Why we use / need

Machine Learning models cannot directly understand a raw date as a meaningful numerical feature.

Breaking a date into Year, Month, and Day allows the model to identify yearly, monthly, and daily patterns.

### When to use

Use these features when analyzing:

- Yearly booking trends
- Monthly booking patterns
- Daily booking behavior
- Seasonal changes in hotel demand

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    r"C:\Users\HP\Sprint_6_Feature_Engineering_-_Feature_Selection\data\hotel_bookings.csv"
)

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [3]:
# Create a complete arrival date

df["arrival_date"] = pd.to_datetime(
    df["arrival_date_year"].astype(str)
    + "-"
    + df["arrival_date_month"]
    + "-"
    + df["arrival_date_day_of_month"].astype(str),
    format="%Y-%B-%d"
)

# Extract Year, Month, and Day

df["Year"] = df["arrival_date"].dt.year
df["Month"] = df["arrival_date"].dt.month
df["Day"] = df["arrival_date"].dt.day

df[
    [
        "arrival_date",
        "Year",
        "Month",
        "Day"
    ]
].head()

  arrival_date  Year  Month  Day
0   2015-07-01  2015      7    1
1   2015-07-01  2015      7    1
2   2015-07-01  2015      7    1
3   2015-07-01  2015      7    1
4   2015-07-01  2015      7    1

### Observation

The arrival date has been converted into a datetime column and separated into Year, Month, and Day.

These features make it easier to analyze booking patterns across different years, months, and days.

## 2. Day of Week

### Explanation

Day of Week identifies which day of the week the hotel booking arrival occurred.

The `arrival_date` column can be used to extract both the numerical day of the week and its name.

### Example

If the arrival date is a Monday:

→ DayOfWeek = 0  
→ DayName = Monday

### Why we use / need

Booking behavior can differ across weekdays and weekends.

This feature helps the model identify weekly booking patterns and differences in hotel demand.

### When to use

Use this feature when analyzing:

- Weekly booking patterns
- Weekday vs weekend demand
- Hotel occupancy trends
- Customer booking behavior

In [4]:
df["DayOfWeek"] = df["arrival_date"].dt.dayofweek
df["DayName"] = df["arrival_date"].dt.day_name()

df[
    [
        "arrival_date",
        "DayOfWeek",
        "DayName"
    ]
].head()

  arrival_date  DayOfWeek    DayName
0   2015-07-01          2  Wednesday
1   2015-07-01          2  Wednesday
2   2015-07-01          2  Wednesday
3   2015-07-01          2  Wednesday
4   2015-07-01          2  Wednesday

### Observation

The day of the week has been extracted from the arrival date.

`DayOfWeek` represents Monday as 0 and Sunday as 6, while `DayName` provides the corresponding day name.

This feature can help identify weekly patterns in hotel bookings.

## 3. Week Number

### Explanation

Week Number shows which week of the year the hotel booking arrival date falls into.

The week number ranges from 1 to 53 depending on the year.

### Example

An arrival date in the first week of the year:

→ WeekNumber = 1

### Why we use / need

Weekly grouping can reduce daily-level noise while still capturing short-term booking patterns.

This feature helps the model identify recurring weekly trends in hotel bookings.

### When to use

Use this feature for:

- Weekly booking analysis
- Demand forecasting
- Occupancy trend analysis
- Seasonal booking patterns
- Campaign or promotion analysis

In [5]:
df["WeekNumber"] = (
    df["arrival_date"]
    .dt.isocalendar()
    .week
)

df[
    [
        "arrival_date",
        "WeekNumber"
    ]
].head()

  arrival_date  WeekNumber
0   2015-07-01          27
1   2015-07-01          27
2   2015-07-01          27
3   2015-07-01          27
4   2015-07-01          27

### Observation

The ISO week number has been extracted from the arrival date.

The `WeekNumber` feature indicates the week of the year in which each hotel booking arrival occurred.

This can help identify weekly booking and demand patterns.

## 4. Quarter

### Explanation

Quarter groups the months of a year into four business quarters:

- Q1 – January to March
- Q2 – April to June
- Q3 – July to September
- Q4 – October to December

### Example

July → Quarter 3

### Why we use / need

Hotels may experience different booking and demand patterns across business quarters.

Quarter-based features provide a broader time grouping than individual months and can help the model identify business cycles.

### When to use

Use this feature for:

- Quarterly booking analysis
- Hotel demand forecasting
- Business reporting
- Seasonal trend analysis
- Comparing booking performance across quarters

In [6]:
df["Quarter"] = df["arrival_date"].dt.quarter

df[
    [
        "arrival_date",
        "Quarter"
    ]
].head()

  arrival_date  Quarter
0   2015-07-01        3
1   2015-07-01        3
2   2015-07-01        3
3   2015-07-01        3
4   2015-07-01        3

### Observation

The arrival date has been converted into a quarter value from 1 to 4.

This feature groups hotel bookings into broader quarterly periods and can help identify booking and demand patterns across different parts of the year.

## 5. Weekend Indicator

### Explanation

Weekend Indicator is a binary feature that shows whether the hotel booking arrival occurred on a weekend.

It represents:

- 1 – Weekend
- 0 – Weekday

### Example

Saturday arrival → IsWeekend = 1

Monday arrival → IsWeekend = 0

### Why we use / need

Hotel booking behavior can differ between weekdays and weekends.

A direct weekend indicator helps the Machine Learning model identify these differences and learn weekly booking patterns.

### When to use

Use this feature when:

- Weekend demand is different from weekday demand.
- Analyzing hotel occupancy patterns.
- Studying customer booking behavior.
- Building hotel demand or cancellation prediction models.

In [7]:
df["IsWeekend"] = (
    df["DayOfWeek"]
    .isin([5, 6])
    .astype(int)
)

df[
    [
        "arrival_date",
        "DayOfWeek",
        "DayName",
        "IsWeekend"
    ]
].head()

  arrival_date  DayOfWeek    DayName  IsWeekend
0   2015-07-01          2  Wednesday          0
1   2015-07-01          2  Wednesday          0
2   2015-07-01          2  Wednesday          0
3   2015-07-01          2  Wednesday          0
4   2015-07-01          2  Wednesday          0

### Observation

The `IsWeekend` feature has been created using the day of the week.

Saturday and Sunday are represented as 1, while weekdays are represented as 0.

This binary feature makes it easier for a Machine Learning model to identify differences between weekend and weekday hotel bookings.

## 6. Month Start / Month End

### Explanation

Month Start and Month End features indicate whether the hotel booking arrival date falls on the first or last day of a month.

They are represented as binary features:

- `IsMonthStart = 1` → First day of the month
- `IsMonthEnd = 1` → Last day of the month

### Example

July 1 → IsMonthStart = 1

July 31 → IsMonthEnd = 1

### Why we use / need

Booking demand can vary around the beginning and end of a month.

These features allow the model to capture possible booking patterns related to month boundaries.

### When to use

Use these features when analyzing:

- Monthly booking patterns
- Hotel demand
- Occupancy trends
- Month-based customer behavior

In [8]:
df["IsMonthStart"] = (
    df["arrival_date"]
    .dt.is_month_start
    .astype(int)
)

df["IsMonthEnd"] = (
    df["arrival_date"]
    .dt.is_month_end
    .astype(int)
)

df[
    [
        "arrival_date",
        "IsMonthStart",
        "IsMonthEnd"
    ]
].head()

  arrival_date  IsMonthStart  IsMonthEnd
0   2015-07-01             1           0
1   2015-07-01             1           0
2   2015-07-01             1           0
3   2015-07-01             1           0
4   2015-07-01             1           0

### Observation

The `IsMonthStart` and `IsMonthEnd` features have been created from the arrival date.

They contain 1 when the booking arrival occurs on the first or last day of the month and 0 otherwise.

These features can help the model identify patterns occurring around monthly boundaries.

## 7. Days Since Event

### Explanation

Days Since Event measures how many days have passed between a fixed reference date and the hotel booking arrival date.

For the Hotel Booking dataset, the earliest arrival date can be used as the reference event.

### Example

First arrival date = January 1  
Booking arrival date = January 10

→ DaysSinceFirstEvent = 9 days

### Why we use / need

A raw date does not directly represent how much time has passed.

Converting the date into the number of elapsed days provides a continuous numerical feature that Machine Learning models can use more easily.

### When to use

Use this feature when tracking:

- Time since the first booking
- Time since a campaign or event
- Booking timeline progression
- Long-term booking trends

In [9]:
# Find the earliest arrival date
first_date = df["arrival_date"].min()

# Calculate days since the first event
df["DaysSinceFirstEvent"] = (
    df["arrival_date"] - first_date
).dt.days

df[
    [
        "arrival_date",
        "DaysSinceFirstEvent"
    ]
].head()

  arrival_date  DaysSinceFirstEvent
0   2015-07-01                    0
1   2015-07-01                    0
2   2015-07-01                    0
3   2015-07-01                    0
4   2015-07-01                    0

### Observation

The number of days from the earliest arrival date has been calculated for each booking.

The first arrival date has a value of 0, while later arrival dates have increasing values.

This converts the date into a continuous time-based feature that can help the model understand the progression of bookings over time.

## 8. Time Difference

### Explanation

Time Difference calculates the gap between consecutive hotel booking arrivals for the same customer.

In the Hotel Booking dataset, `arrival_date` and `customer_type` are available, but there is no `CustomerID` column.

Therefore, a customer-level time difference cannot be calculated directly from the dataset.

For this dataset, we can calculate the difference between consecutive arrival dates after sorting the bookings by date.

### Example

Arrival 1 = January 10  
Arrival 2 = January 15

→ TimeDifference = 5 days

### Why we use / need

Time difference converts consecutive dates into a numerical measure of elapsed time.

It can help identify booking intervals and time-based patterns in the data.

### When to use

Use this feature when:

- Consecutive events need to be compared.
- Booking intervals are important.
- Time-based behavior needs to be analyzed.
- Customer-level transaction history is available.

In [10]:
# Sort bookings by arrival date
df = df.sort_values("arrival_date").copy()

# Calculate the difference between consecutive arrival dates
df["TimeDifferenceDays"] = (
    df["arrival_date"].diff().dt.days
)

df[
    [
        "arrival_date",
        "TimeDifferenceDays"
    ]
].head(10)

      arrival_date  TimeDifferenceDays
0       2015-07-01                 NaN
75559   2015-07-01                 0.0
75560   2015-07-01                 0.0
75561   2015-07-01                 0.0
75562   2015-07-01                 0.0
75563   2015-07-01                 0.0
75564   2015-07-01                 0.0
75565   2015-07-01                 0.0
75566   2015-07-01                 0.0
75558   2015-07-01                 0.0

### Observation

The `TimeDifferenceDays` feature calculates the number of days between consecutive booking arrival dates.

The first row has a missing value because there is no previous arrival date for comparison.

Since the Hotel Booking dataset does not contain a customer identifier, this calculation represents the overall sequence of arrival dates rather than the time difference between purchases for an individual customer.

## 9. Customer Age

### Explanation

Customer Age calculates the age of a customer from their date of birth.

The Hotel Booking dataset does not contain a date of birth column, so an actual customer age cannot be calculated from the available data.

Therefore, unlike the senior notebook, a real Customer Age feature cannot be created for this dataset without additional customer demographic data.

### Why we use / need

Age can be a useful demographic feature because customer behavior and booking preferences may vary across different age groups.

### When to use

Use Customer Age when customer date of birth or age information is available, for example in:

- Customer segmentation
- Personalized recommendations
- Customer behavior analysis
- Risk prediction

In [11]:
# Check whether the dataset contains customer age information

age_columns = [
    column for column in df.columns
    if "age" in column.lower() or "birth" in column.lower()
]

print("Age-related columns:")
print(age_columns)

Age-related columns:
['agent']

### Observation

The Hotel Booking dataset does not contain a customer age or date of birth column.

Therefore, Customer Age cannot be calculated from the available dataset.

In a real-world project, this feature could be created if customer date of birth information were available.

## 10. Customer Tenure

### Explanation

Customer Tenure measures how long a customer has been active since their first booking.

The Hotel Booking dataset does not contain a customer identifier or customer history that can be used to determine an individual customer's first booking.

Therefore, a true customer-level tenure feature cannot be calculated from the available columns.

### Why we use / need

Customer tenure can help distinguish between new and long-term customers.

Longer-tenured customers may have different booking behavior compared with newer customers.

### When to use

Use Customer Tenure when customer history and a customer identifier are available, for example in:

- Customer loyalty analysis
- Customer lifetime value prediction
- Retention modeling
- Customer segmentation

In [12]:
# Check whether a customer identifier is available

customer_id_columns = [
    column for column in df.columns
    if "customer" in column.lower() and "id" in column.lower()
]

print("Customer ID columns:")
print(customer_id_columns)

Customer ID columns:
[]

### Observation

The Hotel Booking dataset does not contain a customer identifier that allows us to track an individual customer's first booking.

Therefore, a true Customer Tenure feature cannot be calculated from this dataset.

In a real-world customer transaction dataset, tenure can be calculated by finding each customer's first transaction date and measuring the time elapsed from that date.

## 11. Recency

### Explanation

Recency measures how many days have passed since a customer's most recent booking or purchase.

The Hotel Booking dataset does not contain a customer identifier, so true customer-level Recency cannot be calculated.

However, the concept can be applied when customer booking history is available.

### Example

Last booking = July 10  
Reference date = July 30

→ Recency = 20 days

### Why we use / need

Recent customers may have different behavior from customers who have not booked for a long time.

Recency is also an important part of the RFM framework:

- Recency
- Frequency
- Monetary

### When to use

Use Recency in:

- Customer segmentation
- Customer retention analysis
- Churn prediction
- Loyalty analysis
- Marketing analytics

In [13]:
# Check whether a customer identifier is available

customer_id_columns = [
    column for column in df.columns
    if "customer" in column.lower() and "id" in column.lower()
]

print("Customer ID columns:")
print(customer_id_columns)

print("\nRecency cannot be calculated at customer level without a customer identifier.")

Customer ID columns:
[]

Recency cannot be calculated at customer level without a customer identifier.

### Observation

The Hotel Booking dataset does not contain a customer identifier.

Therefore, customer-level Recency cannot be calculated reliably from the available data.

In a customer transaction dataset, Recency can be calculated by finding each customer's latest booking date and measuring the number of days between that date and a fixed reference date.

## 12. Frequency

### Explanation

Frequency measures how often a customer makes bookings or transactions.

The Hotel Booking dataset does not contain a customer identifier, so true customer-level booking frequency cannot be calculated.

### Example

If a customer has made 5 bookings:

→ Frequency = 5

### Why we use / need

Customers who book frequently may have different behavior from customers who book only once.

Frequency can therefore provide useful information for understanding customer loyalty and booking behavior.

### When to use

Use Frequency when customer history is available, for example in:

- Customer segmentation
- Loyalty analysis
- Retention modeling
- Customer behavior analysis

In [14]:
# Check whether a customer identifier is available

customer_id_columns = [
    column for column in df.columns
    if "customer" in column.lower() and "id" in column.lower()
]

print("Customer ID columns:")
print(customer_id_columns)

print("\nFrequency cannot be calculated at customer level without a customer identifier.")

Customer ID columns:
[]

Frequency cannot be calculated at customer level without a customer identifier.

### Observation

The Hotel Booking dataset does not contain a customer identifier.

Therefore, customer-level booking Frequency cannot be calculated reliably from the available data.

In a customer transaction dataset, Frequency can be calculated by counting the number of unique bookings or transactions for each customer.

## 13. Seasonality

### Explanation

Seasonality represents recurring patterns that occur during specific periods of the year.

In the Hotel Booking dataset, booking demand can vary across different months and seasons.

The month of the arrival date can be mapped into broader seasons:

- Winter – December, January, February
- Spring – March, April, May
- Summer – June, July, August
- Autumn – September, October, November

### Example

December → Winter

July → Summer

### Why we use / need

Hotel bookings and demand can change depending on the time of year.

Creating a season feature helps the Machine Learning model capture these recurring seasonal patterns.

### When to use

Use Seasonality for:

- Hotel demand forecasting
- Booking pattern analysis
- Occupancy prediction
- Seasonal pricing analysis
- Tourism-related business analysis

In [15]:
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Autumn"


df["Season"] = df["Month"].apply(get_season)

df[
    [
        "arrival_date",
        "Month",
        "Season"
    ]
].head()

      arrival_date  Month  Season
0       2015-07-01      7  Summer
75559   2015-07-01      7  Summer
75560   2015-07-01      7  Summer
75561   2015-07-01      7  Summer
75562   2015-07-01      7  Summer

### Observation

The `Month` feature has been converted into a seasonal category.

Each booking is assigned to Winter, Spring, Summer, or Autumn based on its arrival month.

This feature helps capture recurring seasonal patterns in hotel bookings and can provide useful information for Machine Learning models.