# Module 6 - Interaction Features

## 1. What Are Interaction Features?

Interaction features are new features created by combining two or more existing features using mathematical operations such as multiplication, addition, subtraction, or division.

Example:

Total Stay Nights × ADR → Estimated Stay Value

Why we use / need:

Some relationships become meaningful only when two features are considered together. Interaction features can help the model capture these combined effects.

When to use:

Use interaction features when two or more features together may provide useful information for predicting the target.

However, creating too many interaction features can increase model complexity, introduce noise, and make the model harder to interpret.

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    r"C:\Users\HP\Sprint_6_Feature_Engineering_-_Feature_Selection\data\hotel_bookings.csv"
)

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [3]:
# Create total stay nights
df["total_stay_nights"] = (
    df["stays_in_weekend_nights"] +
    df["stays_in_week_nights"]
)

# Create interaction feature
df["stay_value"] = (
    df["total_stay_nights"] * df["adr"]
)

df[
    ["total_stay_nights", "adr", "stay_value"]
].head()

   total_stay_nights   adr  stay_value
0                  0   0.0         0.0
1                  0   0.0         0.0
2                  1  75.0        75.0
3                  1  75.0        75.0
4                  2  98.0       196.0

### Observation

The `stay_value` feature combines the total stay duration and ADR.

This feature provides additional information about the estimated value of a hotel booking.

## 2. Feature × Feature

Feature × Feature interaction means multiplying two existing features to create a new feature.

Example:

Income × Age → captures the combined effect of income and age.

Hotel Example:

Total Stay Nights × ADR → Estimated Stay Value

Why we use / need:

Multiplication can capture a combined effect where the relationship between two features is more meaningful than considering them separately.

When to use:

Use this interaction when the combined values have a meaningful business or domain relationship.

In [4]:
# Feature × Feature interaction

df["stay_nights_x_adr"] = (
    df["total_stay_nights"] * df["adr"]
)

df[
    ["total_stay_nights", "adr", "stay_nights_x_adr"]
].head()

   total_stay_nights   adr  stay_nights_x_adr
0                  0   0.0                0.0
1                  0   0.0                0.0
2                  1  75.0               75.0
3                  1  75.0               75.0
4                  2  98.0              196.0

### Observation

The `stay_nights_x_adr` feature combines the duration of the stay with the average daily rate.

This gives the model additional information about the overall value of the booking.

## 3. Feature + Feature

Feature + Feature interaction means adding two existing features together to create a combined feature.

Example:

Base Price + Tax → Total Cost

Hotel Example:

Weekend Nights + Weekday Nights → Total Stay Nights

Why we use / need:

Addition is useful when two features represent different parts of the same quantity.

When to use:

Use addition when the combined value has a meaningful business or domain interpretation.

In [5]:
# Feature + Feature interaction

df["total_stay_nights"] = (
    df["stays_in_weekend_nights"] +
    df["stays_in_week_nights"]
)

df[
    [
        "stays_in_weekend_nights",
        "stays_in_week_nights",
        "total_stay_nights"
    ]
].head()

   stays_in_weekend_nights  stays_in_week_nights  total_stay_nights
0                        0                     0                  0
1                        0                     0                  0
2                        0                     1                  1
3                        0                     1                  1
4                        0                     2                  2

### Observation

The `total_stay_nights` feature combines weekend and weekday stay nights.

This gives a single feature representing the complete duration of the hotel booking.

## 4. Feature − Feature

Feature − Feature interaction means subtracting one feature from another to create a difference or gap.

Example:

Expected Price − Actual Price → Price Difference

Hotel Example:

Previous Bookings − Previous Cancellations → Booking History Difference

Why we use / need:

Difference features can show gaps or differences between two related values that may be useful for the model.

When to use:

Use subtraction when the difference between two features has a meaningful business or domain interpretation.

In [6]:
# Feature − Feature interaction

df["booking_history_difference"] = (
    df["previous_bookings_not_canceled"] -
    df["previous_cancellations"]
)

df[
    [
        "previous_bookings_not_canceled",
        "previous_cancellations",
        "booking_history_difference"
    ]
].head()

,previous_bookings_not_canceled,previous_cancellations,booking_history_difference
0,0,0,0
1,0,0,0
2,0,0,0
3,0,0,0
4,0,0,0

### Observation

The `booking_history_difference` feature represents the difference between previous non-canceled bookings and previous cancellations.

This provides a simple summary of the customer's previous booking history.

## 5. Feature / Feature

Feature / Feature interaction means dividing one feature by another to create a ratio.

Example:

Experience / Age → shows the relative amount of experience compared to age.

Hotel Example:

Previous Cancellations / Previous Bookings → Cancellation Ratio

Why we use / need:

Ratio features help represent the relative relationship between two related values.

When to use:

Use division when a rate, proportion, or relative relationship is more meaningful than the individual values.

Care should be taken when the denominator contains zero values.

In [7]:
# Feature / Feature interaction

df["cancellation_ratio"] = (
    df["previous_cancellations"] /
    df["previous_bookings_not_canceled"].replace(0, np.nan)
)

df[
    [
        "previous_cancellations",
        "previous_bookings_not_canceled",
        "cancellation_ratio"
    ]
].head()

   previous_cancellations  previous_bookings_not_canceled  cancellation_ratio
0                       0                               0                 NaN
1                       0                               0                 NaN
2                       0                               0                 NaN
3                       0                               0                 NaN
4                       0                               0                 NaN

### Observation

The `cancellation_ratio` feature represents previous cancellations relative to previous non-canceled bookings.

Zero values in the denominator are replaced with `NaN` to avoid division-by-zero errors.

## 6. Polynomial Features

Polynomial features transform an existing numerical feature by raising it to a power such as square or cube.

Example:

Age² → captures a possible non-linear relationship between age and the target.

Hotel Example:

ADR² → captures a possible non-linear effect of daily room rate.

Why we use / need:

Polynomial features can help linear models represent non-linear relationships that cannot be captured using the original feature alone.

When to use:

Use polynomial features when there is a reason to believe that the relationship between a feature and the target is not simply linear.

Creating too many polynomial features can increase model complexity and may lead to overfitting.

In [8]:
# Create a polynomial feature

df["adr_squared"] = df["adr"] ** 2

df[
    ["adr", "adr_squared"]
].head()

    adr  adr_squared
0   0.0          0.0
1   0.0          0.0
2  75.0       5625.0
3  75.0       5625.0
4  98.0       9604.0

### Observation

The `adr_squared` feature is created by squaring the ADR value.

This provides an additional feature that can help a linear model capture a possible non-linear relationship between ADR and the target.

## 7. Pairwise Interactions

Pairwise interactions create new interaction features between different pairs of numerical features.

Example:

From [Quantity, Price, Age]:

Quantity × Price  
Quantity × Age  
Price × Age

Hotel Example:

Lead Time × ADR  
Lead Time × Total Stay Nights  
ADR × Total Stay Nights

Why we use / need:

Pairwise interactions can help identify combined effects between multiple features.

When to use:

Use pairwise interactions during feature exploration when you want to test whether combinations of features provide useful information.

However, creating interactions for too many features can greatly increase the number of columns, create noise, and make the model unnecessarily complex.

In [10]:
from itertools import combinations

# Make sure total stay nights exists
df["total_stay_nights"] = (
    df["stays_in_weekend_nights"] +
    df["stays_in_week_nights"]
)

# Select numerical features
num_cols = [
    "lead_time",
    "adr",
    "total_stay_nights"
]

# Create pairwise interaction features
for col1, col2 in combinations(num_cols, 2):
    df[f"{col1}_x_{col2}"] = df[col1] * df[col2]

# Display created interaction features
df[
    [
        "lead_time",
        "adr",
        "total_stay_nights",
        "lead_time_x_adr",
        "lead_time_x_total_stay_nights",
        "adr_x_total_stay_nights"
    ]
].head()

,lead_time,adr,total_stay_nights,lead_time_x_adr,lead_time_x_total_stay_nights,adr_x_total_stay_nights
0,342,0.0,0,0.0,0,0.0
1,737,0.0,0,0.0,0,0.0
2,7,75.0,1,525.0,7,75.0
3,13,75.0,1,975.0,13,75.0
4,14,98.0,2,1372.0,28,196.0

### Observation

Pairwise interaction features were created by multiplying selected numerical features.

These features help the model capture combined relationships between different hotel booking attributes.

Pairwise interactions should be used carefully because creating too many combinations can increase model complexity and introduce unnecessary features.

## 8. Domain-Based Interactions

Domain-based interaction features are created using business or domain knowledge.

Example:

Total Spending / Number of Orders → Average Order Value

Hotel Example:

Total Stay Nights × ADR → Estimated Stay Value

Why we use / need:

Domain-based interactions represent meaningful relationships between features. They are easier to understand and explain because they are based on real-world business knowledge.

When to use:

Use domain-based interactions when there is a clear relationship between features that can provide useful information to the Machine Learning model.

Domain-based interactions are generally better than creating random combinations of features.

Too many unnecessary interactions can increase model complexity and introduce noise.

In [11]:
# Create domain-based interaction features

df["estimated_stay_value"] = (
    df["total_stay_nights"] * df["adr"]
)

df["requests_per_night"] = (
    df["total_of_special_requests"] /
    df["total_stay_nights"].replace(0, np.nan)
)

df[
    [
        "total_stay_nights",
        "adr",
        "total_of_special_requests",
        "estimated_stay_value",
        "requests_per_night"
    ]
].head()

,total_stay_nights,adr,total_of_special_requests,estimated_stay_value,requests_per_night
0,0,0.0,0,0.0,NaN
1,0,0.0,0,0.0,NaN
2,1,75.0,0,75.0,0.0
3,1,75.0,0,75.0,0.0
4,2,98.0,1,196.0,0.5

### Observation

Two domain-based interaction features were created.

`estimated_stay_value` combines the total stay nights and ADR to represent the estimated value of the booking.

`requests_per_night` represents the number of special requests relative to the length of the stay.

These features have a clear meaning in the hotel booking domain and can provide useful information to the Machine Learning model.